### ISSUE TITLE
errors when running darwin.js

### ISSUE THREAD

**Issue by DeviaVir** [highvelocityspace/zenbot#19]
_From @gpearson100 on December 21, 2017 14:58_

------------------------

### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: **No**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  **Ubuntu 17.10**
- **Zenbot version**: **4.05**
- **NodeJS version**:  **v8.9.3**
- **Python version**:  **Python 2.7.14**
- **Exact command to reproduce**:
``scripts/genetic_backtester/darwin.js --selector=poloniex.XRP-BTC --days=4 --population=1``

### Describe the problem
The code errors out without generating results.

### Source code / logs

``Generation complete, saving results...
``````
Generation's Best Results
(crossover_vwap) VS Buy and Hold: undefined End Balance: undefined
(cci_srsi) VS Buy and Hold: undefined End Balance: undefined
(srsi_macd) VS Buy and Hold: undefined End Balance: undefined
(macd) VS Buy and Hold: undefined End Balance: undefined
(neural) VS Buy and Hold: undefined End Balance: undefined
(rsi) VS Buy and Hold: undefined End Balance: undefined
(sar) VS Buy and Hold: undefined End Balance: undefined
(speed) VS Buy and Hold: undefined End Balance: undefined
(trend_ema) VS Buy and Hold: undefined End Balance: undefined
(trust_distrust) VS Buy and Hold: undefined End Balance: undefined
(ta_macd) VS Buy and Hold: undefined End Balance: undefined
(ta_ema) VS Buy and Hold: undefined End Balance: undefined


=== Simulating generation 2 ===

Backfilling (might take some time) ...
./zenbot.sh backfill --days=4 poloniex.XRP-BTC
Generation complete, saving results...


Generation's Best Results
/home/greg/zenbot/scripts/genetic_backtester/node_modules/geneticalgorithm/index.js:121
      },scored[0]).phenotype
                  ^

TypeError: Cannot read property 'phenotype' of undefined
    at Object.best (/home/greg/zenbot/scripts/genetic_backtester/node_modules/geneticalgorithm/index.js:121:19)
    at /home/greg/zenbot/scripts/genetic_backtester/darwin.js:575:35
    at Array.forEach (<anonymous>)
    at parallel (/home/greg/zenbot/scripts/genetic_backtester/darwin.js:574:24)
    at end (/home/greg/zenbot/scripts/genetic_backtester/node_modules/run-parallel-limit/index.js:17:15)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

``

_Copied from original issue: carlos8f/zenbot#963_

**Comment by DeviaVir** [comment]
_From @pursehouse on December 24, 2017 5:25_

having the same issue with command

```
./scripts/genetic_backtester/darwin.js --selector="gdax.LTC-USD" --days=1 --currency_capital=10000 --use_strategies=trend_ema --population=1 --order_type=maker
```

```
--==Zenbot 4 Genetic Backtester v0.2==--
Sun, 24 Dec 2017 05:17:59 GMT

Backtesting strategy trend_ema ...
Creating population of 1 ...



=== Simulating generation 1 ===

Backfilling (might take some time) ...
./zenbot.sh backfill --days=1 gdax.LTC-USD
[ 1/1 ] ./zenbot.sh sim gdax.LTC-USD --days=1 --currency_capital=10000 --filename none --strategy=trend_ema --periodLength=102m --min_periods=13 --markup_pct=3.643411730842544 --order_type=maker --sell_stop_pct=0 --buy_stop_pct=19 --profit_stop_enable_pct=0 --profit_stop_pct=19 --trend_ema=20 --oversold_rsi=26 --oversold_rsi_periods=18 --neutral_rate=auto
Generation complete, saving results...


Generation's Best Results
(trend_ema) VS Buy and Hold: -7.48 End Balance: 9581.62505662


=== Simulating generation 2 ===

Backfilling (might take some time) ...
./zenbot.sh backfill --days=1 gdax.LTC-USD
Generation complete, saving results...


Generation's Best Results
/mnt/d/work/3rdparty/zenbot/scripts/genetic_backtester/node_modules/geneticalgorithm/index.js:121
      },scored[0]).phenotype
                  ^

TypeError: Cannot read property 'phenotype' of undefined
    at Object.best (/mnt/d/work/3rdparty/zenbot/scripts/genetic_backtester/node_modules/geneticalgorithm/index.js:121:19)
    at /mnt/d/work/3rdparty/zenbot/scripts/genetic_backtester/darwin.js:576:35
    at Array.forEach (<anonymous>)
    at parallel (/mnt/d/work/3rdparty/zenbot/scripts/genetic_backtester/darwin.js:575:24)
    at end (/mnt/d/work/3rdparty/zenbot/scripts/genetic_backtester/node_modules/run-parallel-limit/index.js:17:15)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
