### ISSUE TITLE
binance order cost = amount * price should be > 0.001 BTC 

### ISSUE THREAD

**Issue by DeviaVir** [highvelocityspace/zenbot#44]
_From @nhancm on December 17, 2017 11:25_

### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Zenbot version**: 4.0.5
- **NodeJS version**: v8.9.3
- **Python version**: 2.7.12
- **Exact command to reproduce**: ./zenbot.sh trade

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in Zenbot or a feature request.

### Source code / logs
An error occurred { Error: binance order cost = amount * price should be > 0.001 BTC {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}
    at binance.handleErrors (/home/zenbot/zenbot/node_modules/ccxt/js/binance.js:627:19)
    at response.text.then.text (/home/zenbot/zenbot/node_modules/ccxt/js/base/Exchange.js:412:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: InvalidOrder] }

Binance API is down! unable to call buy, retrying in 20s
[ { price: '0.00002340',
    size: '29.36043000',
    orig_size: '29.36043000',
    remaining_size: '29.36043000',
    orig_price: '0.00002340',
    cancel_after: 'day',
    product_id: 'ZRX-BTC',
    post_only: true,
    type: 'limit',
    side: 'buy' } ]

_Copied from original issue: carlos8f/zenbot#900_

**Comment by DeviaVir** [comment]
_From @nhancm on December 17, 2017 16:29_

Please apply a fix for check if a current account doesn't have enough balance >= 0.001 BTC let show warning or stop the bot. minimum order BUY/SELL limit at binance.com is 0.001 BTC. thanks

**Comment by DeviaVir** [comment]
_From @carolburri on December 17, 2017 16:38_

this fix is not working for IOTA/BTC

my current settings are: 
 {
    "id": "IOTABTC",
    "asset": "IOTA",
    "currency": "BTC",
    "min_size": "1.00000000",
    "max_size": "100000",
    "increment": "0.001",
    "label": "IOTA/BTC"
  },

Any help would be great!

**Comment by DeviaVir** [comment]
_From @sust4in on December 24, 2017 0:55_

i have this issue too.

**Comment by DeviaVir** [comment]
_From @kroitor on December 26, 2017 9:36_

- https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule
- https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#min_notional

**Comment by kroitor** [comment]
```
{     limits: { amount: { min: 1, max: 90000000 },
                 price: { min: 1e-8, max: 100000 },
                  cost: { min: 0.001, max: undefined } },
   precision: { base: 8, quote: 8, amount: 0, price: 8 },
   tierBased:    false,
  percentage:    true,
       taker:    0.001,
       maker:    0.001,
          id:   "ZRXBTC",
      symbol:   "ZRX/BTC",
        base:   "ZRX",
       quote:   "BTC",
        info: {             symbol:   "ZRXBTC",
                            status:   "TRADING",
                         baseAsset:   "ZRX",
                baseAssetPrecision:    8,
                        quoteAsset:   "BTC",
                    quotePrecision:    8,
                        orderTypes: [ "LIMIT",
                                      "LIMIT_MAKER",
                                      "MARKET",
                                      "STOP_LOSS_LIMIT",
                                      "TAKE_PROFIT_LIMIT" ],
                    icebergAllowed:    true,
                           filters: [ { filterType: "PRICE_FILTER",
                                          minPrice: "0.00000001",
                                          maxPrice: "100000.00000000",
                                          tickSize: "0.00000001"       },
                                      { filterType: "LOT_SIZE",
                                            minQty: "1.00000000",
                                            maxQty: "90000000.00000000",
                                          stepSize: "1.00000000"         },
                                      {  filterType: "MIN_NOTIONAL",
                                        minNotional: "0.00100000"    }      ] },
         lot:    1,
      active:    true                                                            }
```

For ZRX/BTC, MIN_NOTIONAL must be > "0.00100000" BTC.

From above order params:

```29.36043000 ZRX (amount) * 0.00002340 BTC (price) = 0.000687034062 BTC (cost)```
 
Which is less than 0.001BTC.

**Comment by kroitor** [comment]
Also, note, that 29.36043000 won't pass their second filter – LOT_SIZE, the amount should be evenly divisible by lot size with zero remainder. The lot size is 1 ZRX for this pair. 

```
29.36043 ZRX % 1 = 0.36043
```

This will fail as well with a LOT_SIZE error, after you solve the MIN_NOTIONAL error.
