### ISSUE TITLE
The Error at the Binance "More than 1 hours between startTime and endTime"

### ISSUE THREAD

**Issue by DeviaVir** [highvelocityspace/zenbot#71]
_From @muuuuuu2 on December 28, 2017 14:36_

Hi, guys,
While trading, an error occurred below.
Do you know the reason?

I use ubuntu 16.04.

An error occurred { Error: binance GET https://api.binance.com/api/v1/aggTrades?symbol=XRPBTC&startTime=1514038924092&endTime=1514082124092 400 Bad Request {"code":-1127,"msg":"More than 1 hours between startTime and endTime."} (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)
    at binance.defaultErrorHandler (/home/satoko/zenbot/node_modules/ccxt/js/base/Exchange.js:400:15)
    at response.text.then.text (/home/satoko/zenbot/node_modules/ccxt/js/base/Exchange.js:413:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: ExchangeNotAvailable] }

_Copied from original issue: carlos8f/zenbot#1011_

**Comment by Mirabis** [comment]
Running the params through a EPOCH converter I get: 
endtime = GMT: Sunday, December 24, 2017 2:22:04.092 AM
starttime = GMT: Saturday, December 23, 2017 2:22:04.092 PM

https://github.com/binance-exchange/binance-api-node/blob/4b38f8864380fbac375fa883ac9e04aeeaa94b2b/README.md
```
aggTrades
...
Note: If both startTime and endTime are sent, limit should not 
be sent AND the distance between startTime and endTime must be less than 24 hours.
```

Perhaps exactly 24 hours is not allowed?
