### ISSUE TITLE
Binance order errors

### ISSUE THREAD

**Issue by DeviaVir** [highvelocityspace/zenbot#75]
_From @confact on December 15, 2017 5:54_

I get this error in almost every order:
```javascript
An error occurred { Error: binance POST https://api.binance.com/api/v3/order 400 Bad Request {"code":-2010,"msg":"Account has insufficient balance for requested action."} (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)
    at binance.defaultErrorHandler (/home/confact/Documents/code/zenbot/node_modules/ccxt/js/base/Exchange.js:400:15)
    at response.text.then.text (/home/confact/Documents/code/zenbot/node_modules/ccxt/js/base/Exchange.js:413:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: ExchangeNotAvailable] }
```

Is this a bug?

_Copied from original issue: carlos8f/zenbot#876_

**Comment by DeviaVir** [comment]
_From @sfdu on December 15, 2017 6:47_

Do you have enough $ on your account because the first part of the error code is : "Account has insufficient balance for requested action."

**Comment by DeviaVir** [comment]
_From @confact on December 16, 2017 1:22_

I have 400 USD. 

Shouldn't this trigger some rejection of order instead of an error occurred message?

**Comment by DeviaVir** [comment]
_From @rickysahu on December 20, 2017 5:13_

i currently am encountering the same issue and have enough funds to cover the trade. i believe this is an issue with binance's api. has anyone figured out a way around it?
